# Generated by Django 5.2.12 on 2026-04-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('income', 'Thu nhập'), ('expense', 'Chi tiêu')], max_length=10)),
                ('category', models.CharField(max_length=100)),
                ('frequency', models.CharField(choices=[('daily', 'Hàng ngày'), ('weekly', 'Hàng tuần'), ('monthly', 'Hàng tháng')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('next_due_date', models.DateField()),
                ('reminder_days_before', models.IntegerField(default=0, help_text='Số ngày nhắc trước hạn')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
