# Generated by Django 5.2.12 on 2026-04-28 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_recurringtransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('theme_mode', models.CharField(choices=[('light', 'Sáng'), ('dark', 'Tối')], default='light', max_length=10)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('email_notifications', models.BooleanField(default=True)),
                ('large_transaction_notifications', models.BooleanField(default=True)),
                ('budget_notifications', models.BooleanField(default=True)),
                ('currency', models.CharField(choices=[('vnd', 'Đồng Việt Nam (₫)'), ('usd', 'Dollar Mỹ ($)'), ('eur', 'Euro (€)')], default='vnd', max_length=10)),
                ('date_format', models.CharField(choices=[('dd/mm/yyyy', 'DD/MM/YYYY'), ('mm/dd/yyyy', 'MM/DD/YYYY'), ('yyyy-mm-dd', 'YYYY-MM-DD')], default='dd/mm/yyyy', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
