# Generated by Django 5.2.12 on 2026-05-20 02:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_transaction_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtransaction',
            name='cron_expression',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='custom_interval',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='custom_interval_unit',
            field=models.CharField(blank=True, choices=[('days', 'Ngày'), ('weeks', 'Tuần')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='execution_mode',
            field=models.CharField(choices=[('auto', 'Tự động thực hiện'), ('pending', 'Chờ xác nhận')], default='auto', max_length=10),
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='is_last_day_of_month',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='max_occurrences',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='monthly_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='monthly_week',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='monthly_weekday',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Thứ Hai'), (1, 'Thứ Ba'), (2, 'Thứ Tư'), (3, 'Thứ Năm'), (4, 'Thứ Sáu'), (5, 'Thứ Bảy'), (6, 'Chủ Nhật')], null=True),
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='next_run_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='occurrences',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='status',
            field=models.CharField(choices=[('active', 'Hoạt động'), ('paused', 'Tạm dừng'), ('completed', 'Hoàn tất')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='recurring',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='tracker.recurringtransaction'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('posted', 'Đã xác nhận'), ('pending', 'Chờ xác nhận')], default='posted', max_length=10),
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Hàng ngày'), ('weekly', 'Hàng tuần'), ('biweekly', 'Hai tuần một lần'), ('monthly', 'Hàng tháng'), ('quarterly', 'Hàng quý'), ('yearly', 'Hàng năm'), ('custom', 'Tùy chỉnh')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='recurringtransaction',
            index=models.Index(fields=['next_run_date'], name='tracker_rec_next_ru_d2e2a2_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringtransaction',
            index=models.Index(fields=['status'], name='tracker_rec_status_15515c_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringtransaction',
            index=models.Index(fields=['execution_mode'], name='tracker_rec_executi_e80057_idx'),
        ),
    ]
